modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hyventure_mod"
version="Alpha 1.0.0"
displayName="Hyventure Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="TheGreatKingBoo_, TheRealKri_"

[[dependencies.hyventure_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



